workspace:
  base: /workspace
  path: spotisearch

pipeline:
  setup:npm:
    image: node:10-alpine
    commands:
    - npm install

  test:lint:
    image: node:10-alpine
    commands:
    - npm run lint

  test:spec:
    image: weboaks/node-karma-protractor-chrome:alpine-root
    commands:
    - npm run test:ci

  #test:e2e:
  #  image: weboaks/node-karma-protractor-chrome:alpine-root
  #  commands:
  #  - npm run e2e:ci

notify:mail:
  image: drillster/drone-email
  from: ci@mattagohni.de
  host: sslout.df.eu
  when:
    event: push
    status: [changed, failure]
  secrets:
  - source: ci_email_user
    target: plugin_username
  - source: ci_email_password
    target: plugin_password
